export default {
  GET_GAME_MODE: 'GET_GAME_MODE',
  GET_GAME_DELAY: 'GET_GAME_DELAY',
  SET_USERNAME: 'SET_USERNAME',
  FILL_ARRAY: 'FILL_ARRAY',
  MAKE_BLUE: 'MAKE_BLUE',
  MAKE_RED: 'MAKE_RED',
  MAKE_GREEN: 'MAKE_GREEN',
  START_GAME: 'START_GAME',
  END_GAME: 'END_GAME'
}