export default {
  GET_GAME_MODE: 'GET_GAME_MODE',
  GET_GAME_DELAY: 'GET_GAME_DELAY',
  SET_USERNAME: 'SET_USERNAME',
  FILL_ARRAY: 'FILL_ARRAY',
  MAKE_BLUE: 'MAKE_BLUE',
  MAKE_RED: 'MAKE_RED',
  MAKE_GREEN: 'MAKE_GREEN',
  ADD_USER_POINT: 'ADD_USER_POINT',
  ADD_PC_POINT: 'ADD_PC_POINT',
  USER_WINS: 'USER_WINS',
  PC_WINS: 'PC_WINS',
  END_GAME: 'END_GAME',
  RESET_STATE: 'RESET_STATE'
}